import { SquadType } from "@/types";

export const SQUAD_FEATURES: Record<SquadType, string[]> = {
  GAMING: ['chat', 'events', 'tasks', 'polls', 'leaderboard', 'lfg', 'tournaments'],
  STUDY: ['chat', 'events', 'tasks', 'polls', 'resources', 'timer', 'flashcards', 'quiz'],
  STARTUP: ['chat', 'events', 'tasks', 'polls', 'roadmap', 'documents', 'investor-updates', 'equity'],
  CREATIVE: ['chat', 'events', 'tasks', 'polls', 'portfolio', 'critique', 'assets', 'commissions'],
  SPORTS: ['chat', 'events', 'tasks', 'polls', 'lineup', 'playbook', 'stats'],
  BOOK_CLUB: ['chat', 'events', 'tasks', 'polls', 'reading-list', 'discussions'],
  FITNESS: ['chat', 'events', 'tasks', 'polls', 'challenges', 'progress', 'nutrition', 'workouts'],
  OTHER: ['chat', 'events', 'tasks', 'polls'],
};

export const FEATURE_LABELS: Record<string, string> = {
  chat: 'Chat',
  events: 'Events',
  tasks: 'Tasks',
  polls: 'Polls',
  leaderboard: 'Leaderboard',
  lfg: 'LFG',
  tournaments: 'Tournaments',
  resources: 'Resources',
  timer: 'Timer',
  flashcards: 'Flashcards',
  quiz: 'Quiz',
  roadmap: 'Roadmap',
  documents: 'Documents',
  'investor-updates': 'Investor Updates',
  equity: 'Equity',
  portfolio: 'Portfolio',
  critique: 'Critique',
  assets: 'Assets',
  commissions: 'Commissions',
  lineup: 'Lineup',
  playbook: 'Playbook',
  stats: 'Stats',
  'reading-list': 'Reading List',
  discussions: 'Discussions',
  challenges: 'Challenges',
  progress: 'Progress',
  nutrition: 'Nutrition',
  workouts: 'Workouts',
};
